# Generated by Django 4.0.6 on 2023-09-16 04:46

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_result_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(default='huongdansudung', max_length=200)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
