# Generated by Django 4.0.6 on 2023-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0004_patient_remove_note_checked_remove_note_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notequestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notequestion',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notequestion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
