# Generated by Django 4.0.6 on 2023-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0009_doctor_star_doctor_timeclick_doctor_totalstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='totalstar',
            field=models.IntegerField(default=1),
        ),
    ]
