# Generated by Django 4.0.6 on 2023-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0011_remove_patient_salary_patient_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
