# Generated by Django 4.0.6 on 2023-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0012_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
