# Generated by Django 4.0.6 on 2023-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0013_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
