# Generated by Django 4.0.6 on 2023-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0014_alter_patient_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='desc',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
