# Generated by Django 4.0.6 on 2023-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0015_alter_patient_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='totalstar',
            field=models.IntegerField(default=5),
        ),
    ]
