# Generated by Django 4.0.6 on 2023-12-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0016_alter_doctor_totalstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
